const ProjectDB = [
  {
    name: "Pizza Town",
    tools: "fullstack",
    src: "/images/deployed/pizza.PNG",
    alt: "pizza",
    client: "https://github.com/Deepak-Kumar-D/Hackathon-Task-Pizza-Delivery",
    server:
      "https://github.com/Deepak-Kumar-D/Hackathon-Task-Pizza-Delivery_Server",
    host: "https://pizza-town.netlify.app/",
  },
  {
    name: "URL Shortener",
    tools: "fullstack",
    src: "/images/deployed/url.PNG",
    alt: "url",
    client: "https://github.com/Deepak-Kumar-D/Urlshortener-Frontend",
    server: "https://github.com/Deepak-Kumar-D/UrlShortener-Backend",
    host: "https://react-urlshortener.netlify.app/",
  },
  {
    name: "Assign Mentor",
    tools: "fullstack",
    src: "/images/deployed/mentor.PNG",
    alt: "mentor",
    client: "https://github.com/Deepak-Kumar-D/Assign-Mentor-Client",
    server: "https://github.com/Deepak-Kumar-D/Assign-Mentor-Server",
    host: "https://react-assign-mentor.netlify.app/",
  },
  {
    name: "Just Recipe",
    tools: "fullstack",
    src: "/images/deployed/recipe.PNG",
    alt: "recipe",
    client: "https://github.com/Deepak-Kumar-D/React-Recipe-App",
    server: "https://github.com/Deepak-Kumar-D/React-Recipe-App-Server",
    host: "https://react-just-recipe.netlify.app/",
  },
  {
    name: "User Profiles",
    tools: "fullstack",
    src: "/images/deployed/profile.PNG",
    alt: "profile",
    client: "https://github.com/Deepak-Kumar-D/React-Users-Client",
    server: "https://github.com/Deepak-Kumar-D/React-Users-Server",
    host: "https://react-reactusers.netlify.app/",
  },
  {
    name: "WhatsApp Clone",
    tools: "react-firebase",
    src: "/images/deployed/whatsapp.PNG",
    alt: "whatsapp",
    client: "https://github.com/Deepak-Kumar-D/Whatsapp-Clone-2021",
    host: "https://whatsapp-clone-mern-2021.web.app/",
  },
  {
    name: "Currency Exchange",
    tools: "react",
    src: "/images/deployed/currency.PNG",
    alt: "currency",
    client: "https://github.com/Deepak-Kumar-D/React-Currency-Exchange",
    host: "https://react-currency-exchanger.netlify.app/",
  },

  {
    name: "Admin Theme",
    tools: "react",
    src: "/images/deployed/admin.PNG",
    alt: "admin",
    client: "https://github.com/Deepak-Kumar-D/Admin-Theme",
    host: "https://react-admin-theme.netlify.app/",
  },
  {
    name: "Phone Number Validator",
    tools: "react",
    src: "/images/deployed/phone.PNG",
    alt: "phone",
    client: "https://github.com/Deepak-Kumar-D/React-Phone-Number-Validator",
    host: "https://react-phone-number-validator.netlify.app/",
  },
  {
    name: "GitHub Clone",
    tools: "html-javascript",
    src: "/images/deployed/github.PNG",
    alt: "github",
    client: "https://github.com/Deepak-Kumar-D/Hackathon-Task-GITHUB-CLONE",
    host: "https://deepak-kumar-d.github.io/Hackathon-Task-GITHUB-CLONE/",
  },
  {
    name: "Shopping In Style",
    tools: "react",
    src: "/images/deployed/shop.PNG",
    alt: "shop",
    client: "https://github.com/Deepak-Kumar-D/Shopping-in-Style",
    host: "https://shopping-in-style.netlify.app/",
  },
  {
    name: "Calculator",
    tools: "html-javascript",
    src: "/images/deployed/calculator.PNG",
    alt: "calculator",
    client: "https://github.com/Deepak-Kumar-D/Task-10_DOM-Task-1",
    host: "https://deepak-kumar-d.github.io/Task-10_DOM-Task-1/",
  },
];

export default ProjectDB;
